#! /bin/sh

## Multi-version-api packaging:
PG_VERSION=$(pg_config --version |sed -e 's/^PostgreSQL //;s/\.[[:digit:]]\+$//')

LIBPQ_VERSION=5
#replace-gauche-string.pl --api=pg --version=$PG_VERSION

sed -e "s/@pg@/pg-$LIBPQ_VERSION/g;s/@gauche@/gauche/g" \
    debian/control.in > debian/control

# make -f debian/rules debian/control


# provide the   Automake related files ... install-sh

# sort of run Automake(1)
touch Makefile.am
mv -v Makefile.in Makefile.in.real
touch NEWS README ChangeLog AUTHORS
autoreconf --install


export WANT_AUTOCONF_2_5=1
autoconf  --include `gauche-config --ac` configure.in> configure
mv -v Makefile.in.real Makefile.in
chmod +x  ./configure
